In [1]:
import numpy as np
import pandas as pd

from linearmodels import PooledOLS          # Pooled model
from linearmodels import RandomEffects      # Random-effect model
from linearmodels import PanelOLS           # Fixed-effect model
from linearmodels import FirstDifferenceOLS # First difference model

from linearmodels.panel import compare      # Compare the results of multiple models
from statsmodels.api import add_constant    # for matrices of regression design

In [2]:
df = pd.read_csv('Cigar.csv')
df.head()

   state  year  price     pop   pop16   cpi          ndi  sales  pimin
0      1    63   28.6  3383.0  2236.5  30.6  1558.304530   93.9   26.1
1      1    64   29.8  3431.0  2276.7  31.0  1684.073202   95.4   27.5
2      1    65   29.8  3486.0  2327.5  31.5  1809.841875   98.5   28.9
3      1    66   31.5  3524.0  2369.7  32.4  1915.160357   96.4   29.5
4      1    67   31.6  3533.0  2393.7  33.4  2023.546368   95.5   29.6

In [3]:
panel_df = df.set_index(['state', 'year'])
panel_df.head()

            price     pop   pop16   cpi          ndi  sales  pimin
state year
1     63     28.6  3383.0  2236.5  30.6  1558.304530   93.9   26.1
      64     29.8  3431.0  2276.7  31.0  1684.073202   95.4   27.5
      65     29.8  3486.0  2327.5  31.5  1809.841875   98.5   28.9
      66     31.5  3524.0  2369.7  32.4  1915.160357   96.4   29.5
      67     31.6  3533.0  2393.7  33.4  2023.546368   95.5   29.6

# 4 Cigarette Consumption

In [4]:
mod_pl = PooledOLS.from_formula(formula='sales~1+price+pop+pop16+cpi+ndi+pimin', data=panel_df)
res_pl = mod_pl.fit()
res_pl

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  sales   R-squared:                        0.2461
Estimator:                  PooledOLS   R-squared (Between):              0.2814
No. Observations:                1380   R-squared (Within):               0.1682
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.2461
Time:                        01:00:55   Log-likelihood                   -6501.2
Cov. Estimator:            Unadjusted
                                        F-statistic:                      74.717
Entities:                          46   P-value                           0.0000
Avg Obs:                       30.000   Distribution:                  F(6,1373)
Min Obs:                       30.000
Max Obs:                       30.000   F-statistic (robust):             74.717
                                        P-value                           0.0000
Time periods:                      30   Distribution:                  F(6,1373)
Avg Obs:                       46.000
Min Obs:                       46.000
Max Obs:                       46.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      138.62     2.2470     61.692     0.0000      134.21      143.03
price         -1.5276     0.1153    -13.247     0.0000     -1.7539     -1.3014
pop           -0.0025     0.0028    -0.9034     0.3664     -0.0079      0.0029
pop16          0.0024     0.0037     0.6530     0.5139     -0.0048      0.0097
cpi            0.1443     0.0812     1.7767     0.0758     -0.0150      0.3036
ndi            0.0060     0.0006     10.117     0.0000      0.0049      0.0072
pimin          0.5948     0.1274     4.6667     0.0000      0.3447      0.8448
==============================================================================
PanelResults, id: 0x12089400

In [5]:
res_pl.f_statistic

Model F-statistic (homoskedastic)
H0: All parameters ex. constant are zero
Statistic: 74.7167
P-value: 0.0000
Distributed: F(6,1373)
WaldTestStatistic, id: 0x12088c20

In [6]:
res_pl.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 19.7118
P-value: 0.0001
Distributed: chi2(2)
WaldTestStatistic, id: 0x11fae470

In [7]:
res_pl.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 117.6342
P-value: 0.0000
Distributed: chi2(3)
WaldTestStatistic, id: 0x1208cb50

In [8]:
res_pl = mod_pl.fit(cov_type='clustered', cluster_entity=True)

In [9]:
res_pl.f_statistic_robust

Model F-statistic (robust)
H0: All parameters ex. constant are zero
Statistic: 24.7126
P-value: 0.0000
Distributed: F(6,1373)
WaldTestStatistic, id: 0x120595e0

In [10]:
res_pl.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 1.9487
P-value: 0.3774
Distributed: chi2(2)
WaldTestStatistic, id: 0x8a89d60

Влияние не значимо. p-value > 0.05

In [11]:
res_pl.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 9.3636
P-value: 0.0248
Distributed: chi2(3)
WaldTestStatistic, id: 0x120c6eb0

In [12]:
mod_re = RandomEffects.from_formula(formula='sales~1+price+pop+pop16+cpi+ndi+pimin', data=panel_df)
res_re = mod_re.fit()
res_re

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                  sales   R-squared:                        0.4269
Estimator:              RandomEffects   R-squared (Between):             -0.1295
No. Observations:                1380   R-squared (Within):               0.4423
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.0486
Time:                        01:00:56   Log-likelihood                   -5526.1
Cov. Estimator:            Unadjusted
                                        F-statistic:                      170.43
Entities:                          46   P-value                           0.0000
Avg Obs:                       30.000   Distribution:                  F(6,1373)
Min Obs:                       30.000
Max Obs:                       30.000   F-statistic (robust):             170.43
                                        P-value                           0.0000
Time periods:                      30   Distribution:                  F(6,1373)
Avg Obs:                       46.000
Min Obs:                       46.000
Max Obs:                       46.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      126.21     3.8100     33.125     0.0000      118.74      133.68
price         -0.6657     0.0757    -8.7980     0.0000     -0.8141     -0.5173
pop           -0.0063     0.0018    -3.4329     0.0006     -0.0099     -0.0027
pop16          0.0084     0.0023     3.7398     0.0002      0.0040      0.0128
cpi            0.9119     0.0517     17.631     0.0000      0.8104      1.0133
ndi           -0.0050     0.0005    -10.535     0.0000     -0.0059     -0.0040
pimin          0.2226     0.0866     2.5720     0.0102      0.0528      0.3924
==============================================================================
RandomEffectsResults, id: 0x12088590

In [13]:
res_re.f_statistic

Model F-statistic (homoskedastic)
H0: All parameters ex. constant are zero
Statistic: 170.4305
P-value: 0.0000
Distributed: F(6,1373)
WaldTestStatistic, id: 0x120720b0

In [14]:
res_re.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 15.0011
P-value: 0.0006
Distributed: chi2(2)
WaldTestStatistic, id: 0x120ed950

In [15]:
res_re.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 111.8540
P-value: 0.0000
Distributed: chi2(3)
WaldTestStatistic, id: 0x120d45f0

In [16]:
res_re = mod_pl.fit(cov_type='clustered', cluster_entity=True)

In [17]:
res_re.f_statistic_robust

Model F-statistic (robust)
H0: All parameters ex. constant are zero
Statistic: 24.7126
P-value: 0.0000
Distributed: F(6,1373)
WaldTestStatistic, id: 0x120f9dd0

In [18]:
res_re.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 1.9487
P-value: 0.3774
Distributed: chi2(2)
WaldTestStatistic, id: 0x120f97d0

Влияние не значимо. p-value > 0.05

In [19]:
res_re.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 9.3636
P-value: 0.0248
Distributed: chi2(3)
WaldTestStatistic, id: 0x120fa150

In [20]:
mod_fe = PanelOLS.from_formula(formula='sales~1+price+pop+pop16+cpi+ndi+pimin+EntityEffects', data=panel_df, drop_absorbed=True)
res_fe = mod_fe.fit()
res_fe

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                  sales   R-squared:                        0.4426
Estimator:                   PanelOLS   R-squared (Between):             -0.1485
No. Observations:                1380   R-squared (Within):               0.4426
Date:                Wed, Apr 08 2026   R-squared (Overall):              0.0356
Time:                        01:00:56   Log-likelihood                   -5488.0
Cov. Estimator:            Unadjusted
                                        F-statistic:                      175.75
Entities:                          46   P-value                           0.0000
Avg Obs:                       30.000   Distribution:                  F(6,1328)
Min Obs:                       30.000
Max Obs:                       30.000   F-statistic (robust):             175.75
                                        P-value                           0.0000
Time periods:                      30   Distribution:                  F(6,1328)
Avg Obs:                       46.000
Min Obs:                       46.000
Max Obs:                       46.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      125.73     2.4748     50.805     0.0000      120.88      130.59
price         -0.6469     0.0753    -8.5912     0.0000     -0.7946     -0.4991
pop           -0.0064     0.0019    -3.2973     0.0010     -0.0102     -0.0026
pop16          0.0086     0.0023     3.7679     0.0002      0.0041      0.0131
cpi            0.9395     0.0515     18.255     0.0000      0.8386      1.0405
ndi           -0.0053     0.0005    -11.301     0.0000     -0.0063     -0.0044
pimin          0.2184     0.0861     2.5355     0.0113      0.0494      0.3873
==============================================================================

F-test for Poolability: 98.631
P-value: 0.0000
Distribution: F(45,1328)

Included effects: Entity
PanelEffectsResults, id: 0x12089160

In [21]:
res_fe.f_statistic

Model F-statistic (homoskedastic)
H0: All parameters ex. constant are zero
Statistic: 175.7476
P-value: 0.0000
Distributed: F(6,1328)
WaldTestStatistic, id: 0x120fa8d0

In [22]:
res_fe.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 16.1874
P-value: 0.0003
Distributed: chi2(2)
WaldTestStatistic, id: 0x120f9fd0

In [23]:
res_fe.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 128.4518
P-value: 0.0000
Distributed: chi2(3)
WaldTestStatistic, id: 0x8c94e50

In [24]:
res_fe = mod_pl.fit(cov_type='clustered', cluster_entity=True)

In [25]:
res_fe.f_statistic_robust

Model F-statistic (robust)
H0: All parameters ex. constant are zero
Statistic: 24.7126
P-value: 0.0000
Distributed: F(6,1373)
WaldTestStatistic, id: 0x12134e50

In [26]:
res_fe.wald_test(formula='pop = 0, pop16=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 1.9487
P-value: 0.3774
Distributed: chi2(2)
WaldTestStatistic, id: 0x121352d0

Влияние не значимо. p-value > 0.05

In [27]:
res_fe.wald_test(formula='pop = 0, pop16=0, ndi=0')

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 9.3636
P-value: 0.0248
Distributed: chi2(3)
WaldTestStatistic, id: 0x120b6c50