In [1]:
import numpy as np
import pandas as pd

from linearmodels import PooledOLS          # Pooled model
from linearmodels import RandomEffects      # Random-effect model
from linearmodels import PanelOLS           # Fixed-effect model
from linearmodels import FirstDifferenceOLS # First difference model

from linearmodels.panel import compare      # Compare the results of multiple models
from statsmodels.api import add_constant    # for matrices of regression design

In [2]:
df = pd.read_csv('Gasoline.csv')
df.head()

   country  year  lgaspcar  lincomep     lrpmg  lcarpcap
0  AUSTRIA  1960  4.173244 -6.474277 -0.334548 -9.766840
1  AUSTRIA  1961  4.100989 -6.426006 -0.351328 -9.608622
2  AUSTRIA  1962  4.073177 -6.407308 -0.379518 -9.457257
3  AUSTRIA  1963  4.059509 -6.370679 -0.414251 -9.343155
4  AUSTRIA  1964  4.037689 -6.322247 -0.445335 -9.237739

In [3]:
panel_df = df.set_index(['country', 'year'])
panel_df.head()

              lgaspcar  lincomep     lrpmg  lcarpcap
country year
AUSTRIA 1960  4.173244 -6.474277 -0.334548 -9.766840
        1961  4.100989 -6.426006 -0.351328 -9.608622
        1962  4.073177 -6.407308 -0.379518 -9.457257
        1963  4.059509 -6.370679 -0.414251 -9.343155
        1964  4.037689 -6.322247 -0.445335 -9.237739

In [4]:
mod_pl = PooledOLS.from_formula(formula='lgaspcar~1+lincomep+lrpmg+lcarpcap', data=panel_df)
res_pl = mod_pl.fit()
res_pl

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:               lgaspcar   R-squared:                        0.8549
Estimator:                  PooledOLS   R-squared (Between):              0.8771
No. Observations:                 342   R-squared (Within):               0.7435
Date:                Wed, Mar 11 2026   R-squared (Overall):              0.8549
Time:                        20:00:26   Log-likelihood                    50.493
Cov. Estimator:            Unadjusted
                                        F-statistic:                      664.00
Entities:                          18   P-value                           0.0000
Avg Obs:                       19.000   Distribution:                   F(3,338)
Min Obs:                       19.000
Max Obs:                       19.000   F-statistic (robust):             664.00
                                        P-value                           0.0000
Time periods:                      19   Distribution:                   F(3,338)
Avg Obs:                       18.000
Min Obs:                       18.000
Max Obs:                       18.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      2.3913     0.1169     20.450     0.0000      2.1613      2.6213
lincomep       0.8900     0.0358     24.855     0.0000      0.8195      0.9604
lrpmg         -0.8918     0.0303    -29.418     0.0000     -0.9514     -0.8322
lcarpcap      -0.7634     0.0186    -41.023     0.0000     -0.8000     -0.7268
==============================================================================
PanelResults, id: 0x1d0bcdce250

In [5]:
mod_re = RandomEffects.from_formula(formula='lgaspcar~1+lincomep+lrpmg+lcarpcap', data=panel_df)
res_re = mod_re.fit()
res_re

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:               lgaspcar   R-squared:                        0.8293
Estimator:              RandomEffects   R-squared (Between):              0.7099
No. Observations:                 342   R-squared (Within):               0.8363
Date:                Wed, Mar 11 2026   R-squared (Overall):              0.7309
Time:                        20:00:27   Log-likelihood                    320.02
Cov. Estimator:            Unadjusted
                                        F-statistic:                      547.40
Entities:                          18   P-value                           0.0000
Avg Obs:                       19.000   Distribution:                   F(3,338)
Min Obs:                       19.000
Max Obs:                       19.000   F-statistic (robust):             547.40
                                        P-value                           0.0000
Time periods:                      19   Distribution:                   F(3,338)
Avg Obs:                       18.000
Min Obs:                       18.000
Max Obs:                       18.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      1.9967     0.1843     10.832     0.0000      1.6341      2.3593
lincomep       0.5550     0.0591     9.3861     0.0000      0.4387      0.6713
lrpmg         -0.4204     0.0400    -10.515     0.0000     -0.4990     -0.3418
lcarpcap      -0.6068     0.0255    -23.784     0.0000     -0.6570     -0.5567
==============================================================================
RandomEffectsResults, id: 0x1d0bd8a4110

In [6]:
mod_fe = PanelOLS.from_formula(formula='lgaspcar~1+lincomep+lrpmg+lcarpcap+EntityEffects', data=panel_df, drop_absorbed=True)
res_fe = mod_fe.fit()
res_fe

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:               lgaspcar   R-squared:                        0.8396
Estimator:                   PanelOLS   R-squared (Between):              0.5424
No. Observations:                 342   R-squared (Within):               0.8396
Date:                Wed, Mar 11 2026   R-squared (Overall):              0.5917
Time:                        20:00:27   Log-likelihood                    340.33
Cov. Estimator:            Unadjusted
                                        F-statistic:                      560.09
Entities:                          18   P-value                           0.0000
Avg Obs:                       19.000   Distribution:                   F(3,321)
Min Obs:                       19.000
Max Obs:                       19.000   F-statistic (robust):             560.09
                                        P-value                           0.0000
Time periods:                      19   Distribution:                   F(3,321)
Avg Obs:                       18.000
Min Obs:                       18.000
Max Obs:                       18.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      2.4027     0.2253     10.664     0.0000      1.9594      2.8459
lincomep       0.6622     0.0734     9.0242     0.0000      0.5179      0.8066
lrpmg         -0.3217     0.0441    -7.2950     0.0000     -0.4085     -0.2349
lcarpcap      -0.6405     0.0297    -21.580     0.0000     -0.6989     -0.5821
==============================================================================

F-test for Poolability: 83.961
P-value: 0.0000
Distribution: F(17,321)

Included effects: Entity
PanelEffectsResults, id: 0x1d0bd8d2f10

In [7]:
mod_fd = FirstDifferenceOLS.from_formula(formula='lgaspcar~lincomep+lrpmg+lcarpcap', data=panel_df)
res_fd = mod_fd.fit()
res_fd

                     FirstDifferenceOLS Estimation Summary
================================================================================
Dep. Variable:               lgaspcar   R-squared:                        0.5117
Estimator:         FirstDifferenceOLS   R-squared (Between):              0.8814
No. Observations:                 324   R-squared (Within):               0.8231
Date:                Wed, Mar 11 2026   R-squared (Overall):              0.8813
Time:                        20:00:27   Log-likelihood                    512.74
Cov. Estimator:            Unadjusted
                                        F-statistic:                      112.11
Entities:                          18   P-value                           0.0000
Avg Obs:                       19.000   Distribution:                   F(3,321)
Min Obs:                       19.000
Max Obs:                       19.000   F-statistic (robust):             112.11
                                        P-value                           0.0000
Time periods:                      19   Distribution:                   F(3,321)
Avg Obs:                       18.000
Min Obs:                       18.000
Max Obs:                       18.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
lincomep       0.3785     0.0791     4.7832     0.0000      0.2228      0.5341
lrpmg         -0.2487     0.0322    -7.7210     0.0000     -0.3121     -0.1853
lcarpcap      -0.5570     0.0360    -15.486     0.0000     -0.6277     -0.4862
==============================================================================
PanelResults, id: 0x1d0bd8e6690

In [8]:
df = pd.read_csv('Wages.csv')
df.head()

,exp,wks,bluecol,ind,south,smsa,married,sex,union,ed,black,lwage,id,time
0,3,32,no,0,yes,no,yes,male,no,9,no,5.56068,1,1
1,4,43,no,0,yes,no,yes,male,no,9,no,5.72031,1,2
2,5,40,no,0,yes,no,yes,male,no,9,no,5.99645,1,3
3,6,39,no,0,yes,no,yes,male,no,9,no,5.99645,1,4
4,7,42,no,1,yes,no,yes,male,no,9,no,6.06146,1,5

In [9]:
panel_df = df.set_index(['id', 'time'])
panel_df.head()

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no

           lwage
id time
1  1     5.56068
   2     5.72031
   3     5.99645
   4     5.99645
   5     6.06146

In [10]:
mod_pl = PooledOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks', data=panel_df)
res_pl = mod_pl.fit()
res_pl.params.round(3)

Intercept      4.908
ed             0.076
exp            0.045
I(exp ** 2)   -0.001
wks            0.006
Name: parameter, dtype: float64

In [11]:
mod_re = RandomEffects.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks', data=panel_df)
res_re = mod_re.fit()
res_re.params.round(3)

Intercept      3.830
ed             0.112
exp            0.089
I(exp ** 2)   -0.001
wks            0.001
Name: parameter, dtype: float64

In [16]:
mod_fe = PanelOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+EntityEffects', data=panel_df, drop_absorbed=True)
res_fe = mod_fe.fit()
res_fe.params.round(3)

C:\Users\stud.LIMM\AppData\Local\Temp\ipykernel_6936\2350003073.py:2: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

ed

  res_fe = mod_fe.fit()

Intercept      4.596
exp            0.114
I(exp ** 2)   -0.000
wks            0.001
Name: parameter, dtype: float64

In [17]:
mod_pl = PooledOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa', data=panel_df)
res_pl = mod_pl.fit()
res_pl.params.round(3)

Intercept       4.955
ed              0.070
exp             0.045
I(exp ** 2)    -0.001
wks             0.006
south[T.yes]   -0.102
smsa[T.yes]     0.118
Name: parameter, dtype: float64

In [18]:
mod_re = RandomEffects.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa', data=panel_df)
res_re = mod_re.fit()
res_re.params.round(3)

Intercept       3.890
ed              0.111
exp             0.088
I(exp ** 2)    -0.001
wks             0.001
south[T.yes]   -0.022
smsa[T.yes]    -0.037
Name: parameter, dtype: float64

In [20]:
mod_fe = PanelOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa+EntityEffects', data=panel_df, drop_absorbed=True)
res_fe = mod_fe.fit()
res_fe.params.round(3)

C:\Users\stud.LIMM\AppData\Local\Temp\ipykernel_6936\2854555456.py:2: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

ed

  res_fe = mod_fe.fit()

Intercept       4.626
exp             0.114
I(exp ** 2)    -0.000
wks             0.001
south[T.yes]    0.006
smsa[T.yes]    -0.043
Name: parameter, dtype: float64