In [1]:
import pandas as pd

from linearmodels import PooledOLS          # Pooled model
from linearmodels import RandomEffects      # Random-effect model
from linearmodels import PanelOLS           # Fixed-effect model
from linearmodels import FirstDifferenceOLS # First difference model

from linearmodels.panel import compare # Compare the results of multiple models

In [2]:
# Загрузим данные
df = pd.read_csv('Wages.csv')
df.head(20)

,exp,wks,bluecol,ind,south,smsa,married,sex,union,ed,black,lwage,id,time
0,3,32,no,0,yes,no,yes,male,no,9,no,5.56068,1,1
1,4,43,no,0,yes,no,yes,male,no,9,no,5.72031,1,2
2,5,40,no,0,yes,no,yes,male,no,9,no,5.99645,1,3
3,6,39,no,0,yes,no,yes,male,no,9,no,5.99645,1,4
4,7,42,no,1,yes,no,yes,male,no,9,no,6.06146,1,5
5,8,35,no,1,yes,no,yes,male,no,9,no,6.17379,1,6
6,9,32,no,1,yes,no,yes,male,no,9,no,6.24417,1,7
7,30,34,yes,0,no,no,yes,male,no,11,no,6.16331,2,1
8,31,27,yes,0,no,no,yes,male,no,11,no,6.21461,2,2
9,32,33,yes,1,no,no,yes,male,yes,11,no,6.26340,2,3
10,33,30,yes,1,no,no,yes,male,no,11,no,6.54391,2,4
11,34,30,yes,1,no,no,yes,male,no,11,no,6.69703,2,5
12,35,37,yes,1,no,no,yes,male,no,11,no,6.79122,2,6
13,36,30,yes,1,no,no,yes,male,no,11,no,6.81564,2,7
14,6,50,yes,1,no,no,yes,male,yes,12,no,5.65249,3,1
15,7,51,yes,1,no,no,yes,male,yes,12,no,6.43615,3,2
16,8,50,yes,1,no,no,yes,male,yes,12,no,6.54822,3,3
17,9,52,yes,1,no,no,yes,male,yes,12,no,6.60259,3,4
18,10,52,yes,1,no,no,yes,male,yes,12,no,6.69580,3,5
19,11,52,yes,1,no,no,no,male,yes,12,no,6.77878,3,6

In [3]:
df.shape

(4165, 14)

In [6]:
# Зададим структуру панельных данных
panel_df = df.set_index(['id', 'time'])
panel_df.head(20)

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no
   6       8   35      no    1   yes   no     yes  male    no   9    no
   7       9   32      no    1   yes   no     yes  male    no   9    no
2  1      30   34     yes    0    no   no     yes  male    no  11    no
   2      31   27     yes    0    no   no     yes  male    no  11    no
   3      32   33     yes    1    no   no     yes  male   yes  11    no
   4      33   30     yes    1    no   no     yes  male    no  11    no
   5      34   30     yes    1    no   no     yes  male    no  11    no
   6      35   37     yes    1    no   no     yes  male    no  11    no
   7      36   30     yes    1    no   no     yes  male    no  11    no
3  1       6   50     yes    1    no   no     yes  male   yes  12    no
   2       7   51     yes    1    no   no     yes  male   yes  12    no
   3       8   50     yes    1    no   no     yes  male   yes  12    no
   4       9   52     yes    1    no   no     yes  male   yes  12    no
   5      10   52     yes    1    no   no     yes  male   yes  12    no
   6      11   52     yes    1    no   no      no  male   yes  12    no

           lwage
id time
1  1     5.56068
   2     5.72031
   3     5.99645
   4     5.99645
   5     6.06146
   6     6.17379
   7     6.24417
2  1     6.16331
   2     6.21461
   3     6.26340
   4     6.54391
   5     6.69703
   6     6.79122
   7     6.81564
3  1     5.65249
   2     6.43615
   3     6.54822
   4     6.60259
   5     6.69580
   6     6.77878

In [8]:
panel_df['d2_wks'] = panel_df.groupby(level=0)['wks'].diff().diff()
panel_df.head(20)

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no
   6       8   35      no    1   yes   no     yes  male    no   9    no
   7       9   32      no    1   yes   no     yes  male    no   9    no
2  1      30   34     yes    0    no   no     yes  male    no  11    no
   2      31   27     yes    0    no   no     yes  male    no  11    no
   3      32   33     yes    1    no   no     yes  male   yes  11    no
   4      33   30     yes    1    no   no     yes  male    no  11    no
   5      34   30     yes    1    no   no     yes  male    no  11    no
   6      35   37     yes    1    no   no     yes  male    no  11    no
   7      36   30     yes    1    no   no     yes  male    no  11    no
3  1       6   50     yes    1    no   no     yes  male   yes  12    no
   2       7   51     yes    1    no   no     yes  male   yes  12    no
   3       8   50     yes    1    no   no     yes  male   yes  12    no
   4       9   52     yes    1    no   no     yes  male   yes  12    no
   5      10   52     yes    1    no   no     yes  male   yes  12    no
   6      11   52     yes    1    no   no      no  male   yes  12    no

           lwage  d_wks  d2_wks
id time
1  1     5.56068    NaN     NaN
   2     5.72031   11.0     NaN
   3     5.99645   -3.0   -14.0
   4     5.99645   -1.0     2.0
   5     6.06146    3.0     4.0
   6     6.17379   -7.0   -10.0
   7     6.24417   -3.0     4.0
2  1     6.16331    NaN     NaN
   2     6.21461   -7.0     NaN
   3     6.26340    6.0    13.0
   4     6.54391   -3.0    -9.0
   5     6.69703    0.0     3.0
   6     6.79122    7.0     7.0
   7     6.81564   -7.0   -14.0
3  1     5.65249    NaN     NaN
   2     6.43615    1.0     NaN
   3     6.54822   -1.0    -2.0
   4     6.60259    2.0     3.0
   5     6.69580    0.0    -2.0
   6     6.77878    0.0     0.0

In [9]:
panel_df['lag_wks'] = panel_df.groupby(level=0)['wks'].shift()
panel_df.head(20)

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no
   6       8   35      no    1   yes   no     yes  male    no   9    no
   7       9   32      no    1   yes   no     yes  male    no   9    no
2  1      30   34     yes    0    no   no     yes  male    no  11    no
   2      31   27     yes    0    no   no     yes  male    no  11    no
   3      32   33     yes    1    no   no     yes  male   yes  11    no
   4      33   30     yes    1    no   no     yes  male    no  11    no
   5      34   30     yes    1    no   no     yes  male    no  11    no
   6      35   37     yes    1    no   no     yes  male    no  11    no
   7      36   30     yes    1    no   no     yes  male    no  11    no
3  1       6   50     yes    1    no   no     yes  male   yes  12    no
   2       7   51     yes    1    no   no     yes  male   yes  12    no
   3       8   50     yes    1    no   no     yes  male   yes  12    no
   4       9   52     yes    1    no   no     yes  male   yes  12    no
   5      10   52     yes    1    no   no     yes  male   yes  12    no
   6      11   52     yes    1    no   no      no  male   yes  12    no

           lwage  d_wks  d2_wks  lag_wks
id time
1  1     5.56068    NaN     NaN      NaN
   2     5.72031   11.0     NaN     32.0
   3     5.99645   -3.0   -14.0     43.0
   4     5.99645   -1.0     2.0     40.0
   5     6.06146    3.0     4.0     39.0
   6     6.17379   -7.0   -10.0     42.0
   7     6.24417   -3.0     4.0     35.0
2  1     6.16331    NaN     NaN      NaN
   2     6.21461   -7.0     NaN     34.0
   3     6.26340    6.0    13.0     27.0
   4     6.54391   -3.0    -9.0     33.0
   5     6.69703    0.0     3.0     30.0
   6     6.79122    7.0     7.0     30.0
   7     6.81564   -7.0   -14.0     37.0
3  1     5.65249    NaN     NaN      NaN
   2     6.43615    1.0     NaN     50.0
   3     6.54822   -1.0    -2.0     51.0
   4     6.60259    2.0     3.0     50.0
   5     6.69580    0.0    -2.0     52.0
   6     6.77878    0.0     0.0     52.0